let sidemenu = $('#sidemenu')
let menuToggle = $('#menuToggle');
let header = $('#header');
let content = $('#content');
let preloader = $('#preloader');
let wrapper = $('#wrapper');
let lightbox = $('#lightbox');
let lightboxDialog = $('#lightbox .dialog');
let lightboxDialogContent = $('#lightbox .dialog .content');
let lightboxCancelBtn = $('#lightbox .dialog .cancel');
let lightboxOkBtn = $('#lightbox .dialog .success');
let addonTopic = $('#addonTopic');
