sidemenu = $('#sidemenu')
menuToggle = $('#menuToggle');
header = $('#header');
content = $('#content');
lightbox = $('#lightbox');
lightboxDialog = $('#lightbox .dialog');
lightboxDialogContent = $('#lightbox .dialog .content');
lightboxCancelBtn = $('#lightbox .dialog .cancel');
lightboxOkBtn = $('#lightbox .dialog .success');
